# Generated by Django 3.2 on 2021-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRegionCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('national_day', models.DateField(blank=True, null=True)),
                ('country_code2', models.CharField(db_collation='utf8_general_ci', max_length=2)),
                ('country_code3', models.CharField(db_collation='utf8_general_ci', max_length=3)),
                ('region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'my_region_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
    ]
