# Generated by Django 3.2 on 2021-04-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myregioncountries_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': False, 'permissions': [('can_associate_states', 'Can associate states')]},
        ),
    ]
