# Generated by Django 3.2 on 2021-05-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_countries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': False, 'permissions': [('view_countries_permissions', 'Can view countries permissions')]},
        ),
    ]
