# Generated by Django 3.2.4 on 2021-06-06 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_countries_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Continents',
        ),
        migrations.RemoveField(
            model_name='countrylanguages',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrystats',
            name='country',
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='MyRegionCountries',
        ),
        migrations.DeleteModel(
            name='RegionAreas',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.DeleteModel(
            name='States',
        ),
        migrations.DeleteModel(
            name='Vips',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='CountryLanguages',
        ),
        migrations.DeleteModel(
            name='CountryStats',
        ),
    ]
